config/routes.rb
Rails.application.routes.draw do

root 'pages#home'
get 'about', to: 'pages#about'
resources :articles
get 'signup', to: 'users#new'

resources :users, except: [:new]
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

    belongs_to :user
    
    validates :title, presence: true, length: {minimum:6}
    validates :client_name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy

    validates :username, presence: true, length: {minimum:4, maximum:25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, uniqueness: { case_sensitive: false }, format: {with: VALID_EMAIL_REGEX }

    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
 
     end


    def logged_in?
        !!current_user
    end


    def require_user
        if !logged_in?
        flash[:notice] =  "No tiene permisos para realizar esta acción"
        redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :require_same_user, only: %i[ edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "¡Itinerario creado con éxito!" }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "El Itinerario ha sido eliminado" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :client_name, :email, :phone, :travellers)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
      flash[:alert] =  "No tiene permisos para realizar esta acción"
      redirect_to @article
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password].downcase)
        session[:user_id] = user.id
        flash[:notice] = "Bienvenid@"
        redirect_to user
        else
        flash[:alert] =  "Email o contraseña incorrectos"
        redirect_to login_path
    end
    end


    def destroy
        session[:user_id] = nil
        flash[:notice] = "¡Gracias por utilizar TRIPSO!"
        redirect_to login_path
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[ create new index]
  before_action :require_same_user, only: %i[ edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 8)
  end

  # GET /users/1 or /users/1.json
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to articles_path, notice: "¡Bienvenid@ #{@user.username} a tus artículos!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Usuario editado con éxito" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] =  "El usuario y sus itinerarios han sido eliminados"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] =  "No tienes permiso para realizar esta acción"
        redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripción</th>
      <th>De</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= truncate(article.description, lenght:4) %></td>
      <td><%= link_to article.user.username, user_path(article.user)%></td>
      <td>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
      <%= link_to "Editar", edit_article_path(article), class:"btn btn-success" %>
      <td><%= button_to "Eliminar Itinerario", article, class:"btn btn-danger", method: :delete, form: { data: { turbo_confirm:"¿Seguro quieres eliminar este Articulo?"}} %></td>
      <% end %>
      </td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>

  <div class="container mb-3 rondel">
  <%= render 'shared/errors', obj: @article %><br>

    <div class="row mt-3">
    <div class="col-12">
      <div class="h5 border-bottom mb-3 font-weight-bold">Paso 1 - Primeros Detalles</div>
    </div>
  </div>
  
  <div class="col-4">
  <div class="form-label"><br>
    <%= form.label :Nombre_Itinerario, class: "col-form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :Nombre_del_cliente, class: "col-form-label" %>
    <%= form.text_field :client_name, class: "form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :Mail_del_cliente, class: "col-form-label" %>
    <%= form.email_field :email, class: "form-control", placeholder: "ejemplo@mail.com" %>
  </div>

  <div class="form-label">
    <%= form.label :Teléfono_del_cliente, class: "col-form-label" %>
    <%= form.phone_field :phone, class: "form-control"%>
  </div>

  <div class="form-label">
    <%= form.label :Número_de_viajeros, class: "col-form-label" %>
    <%= form.text_field :travellers, class: "form-control" %>
  </div>
  </div>

  <div class="form-label">
    <%= form.label :Observaciones, class: "mb-2 col-form-label" %>
    <%= form.text_area :description, rows:4, class: "form-control" %>
  </div>

  <div>
    <button type="submit" class="btn btn-success mb-3">Guardar</button><br><br>
  </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<br><br>
<h3 style="color: rgb(6, 15, 109)" class="container text-center">Editar Itinerario</h3><br>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1 class="limbo text-center">Itinerarios</h1>

<div id="articles">
    
    <%= render 'article' %>

</div><br>

   <div class="flickr_pagination">

    <%= will_paginate @articles, :container => false %>
  </div>

<%= link_to "Crear Itinerario", new_article_path %>
</div>

app/views/articles/new.html.erb
<br><br>
<div class= "container text-center">
<h3 style="color: rgb(6, 15, 109)">Itinerario</h3>
</div>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p><br>

<div class= "container">
<div class="card">
  <div class="card-header">Itinerario de viaje: <%= @article.title.upcase %>
  <p></p><br>
  <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#">Primeros detalles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Vuelos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Hospedaje</a>
      </li>
      <li class="nav-item">
        <a class="nav-link">Traslados</a>
      </li>
      <li class="nav-item">
        <a class="nav-link">Planificación</a>
      </li>
    </ul>
  </div><br>
  <div class="row mt-3">
    <div class="col-12">
      <div class="h5 border-bottom mb-3 font-weight-bold"> - Primeros Detalles</div>
    </div>
  </div>
  <div class="card-body">
    <div class="card-text bold">Cliente:</div><p class="card-text"><%= (@article.client_name) %></p>
    <div class="card-text bold">Mail:</div><p class="card-text"><%= (@article.email) %></p>
    <div class="card-text bold">Teléfono:</div><p class="card-text"><%= (@article.phone) %></p>
    <div class="card-text bold">Número de viajeros:</div><p class="card-text"><%= (@article.travellers) %></p>
    <div class="card-text bold">Observaciones:</div><p class="card-text"><%= (@article.description) %></p><br>
  


    <% if logged_in? && (@article.user == @current_user || @current_user.admin?) %>
      <td><%= link_to "Editar", edit_article_path(@article), class:"btn btn-success" %></td>
      <% end %>
  </div>
  <div class="card-footer text-muted">Creado hace: <%= time_ago_in_words(@article.created_at)%>
  </div>
</div>
</div><br>

  <td><%= link_to "Volver", articles_path %></td>
  <% if logged_in? && @article.user == @current_user %>
  <td><%= button_to "Eliminar Itinerario", @article, method: :delete, form: { data: { turbo_confirm:"¿Seguro quieres eliminar este Articulo?"}} %></td>
  <% end %>
 </tr>
  </table>
  </div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg" style="background-color: rgb(9, 3, 84);">
  <div class="container-fluid">
    <%= link_to image_tag("tripsoblan.png", height: 50, :alt => "logo"), "/" %>
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="/about">¿Quienes Somos?</a>
        </li>
        <% if logged_in? %>
        <li class="nav-item ">
          <a class="nav-link text-white" href="/articles">Itinerarios</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link text-white" href="/users">Asesores</a>
        </li>
        <% end %>
        <% if logged_in? %>

        <li class="nav-item ">
          <%= link_to 'logout', logout_path, class:"nav-link text-white", method: :delete %>
        </li>
        <% else %>
          <li class="nav-item ">
          <a class="nav-link text-white" href="/login">Login</a>
        </li>
          <li class="nav-item ">
          <a class="nav-link text-white" href="/signup">Registrate</a>
        </li>
        <% end %>
      </ul>
      <% if logged_in? %>
        <li class="nav-link dropdown text-end">
          <%= link_to current_user.username, user_path(current_user), class:"nav-link text-white" if logged_in? %>
        </li>
        <li class="nav-link text-white text-end">
        <%= "(ADMIN)" if current_user.admin? %>
        </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
   <%= render 'layouts/navigation' %>
   <%= yield %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class= "jumb text-center" id="home-container">
<h1>Somos una empresa dedicada al diseño</h1>
<p class="text-white">Asi es como nos manejamos</p>

app/views/pages/home.html.erb
<p style="color: green"><%= notice %></p>

<div class= "jumb text-center" id="home-container">
<%= image_tag "tripso.png", height: 150 %>


<h1 class="didom">Itinerarios de viaje online</h1><br><br>

<p>
      <a class="btn btn-success" href="/signup">Registrate</a>
    </p>
</div>

app/views/shared/_errors.html.erb
  <% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <h2><%= pluralize(@article.errors.count, "error") %> al guardar este artículo:</h2>

      <ul>
        <% obj.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container text-center">
  <div class="mb-3">
    <%= form.label :usuario, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>
  
  <div class="mb-3">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit(@user.new_record? ? "Registrarme": "Editar", class: "btn btn-success mb-3")%><br><br>
  </div>
</div>

<% end %>

app/views/users/_user.html.erb
<div class="container">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Asesor</th>
      <th>Email</th>
      <th>Itinerarios</th>
      <th>Miembro hace:</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user%></td>
      <td><%= user.email %></td>
      <td><%= user.articles.count %></td>
      <td><%= time_ago_in_words(user.created_at) %></td>
      <td>

      <% if logged_in? %>
      <% if user == current_user %>
      <%= link_to "Editar", edit_user_path(user), class:"btn btn-success" %>
      <% end %>
      <% if current_user.admin? %>
      <td><%= button_to "Eliminar", user, class:"btn btn-danger", method: :delete, form: { data: { turbo_confirm:"¿Seguro quieres eliminar este Usuario?"}} %></td>
      <% end %>
      </td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/edit.html.erb
<br>
<div class="container">
<h1 class="limbo text-center">Editar perfil</h1>

<%= render "form", user: @user %>

<br>


  <%= link_to "Ver usuario", @user %> |
  <%= link_to "Volver", users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1 class="limbo text-center">Asesores de viaje</h1>
    <%= render 'users/user' %><br>

  <div class="flickr_pagination">

    <%= will_paginate @users, :container => false %>
  </div>


</div>

app/views/users/new.html.erb
<br>
<div  class="container text-center">
<%= image_tag "tripso.png", height: 150 %>

<%= render "form", user: @user %>

<br>


  <%= link_to "Pagina principal", root_path %>
</div>

app/views/users/show.html.erb
<div class= "container">

<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<div class="card text-center">
  <div class="card-header"><%= @user.username %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(@user.email) %></p>
    <% if logged_in? && @user == @current_user %>
      <td><%= link_to "Editar", edit_user_path(@user), class:"btn btn-success" %></td>
    <% end %>  
      <td><%= link_to "Volver", users_path, class:"btn btn-success" %></td>
  </div>
  <div class="card-footer text-muted"><%= time_ago_in_words(@user.created_at)%>
  </div>
</div>
</div><br>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div> 

 </tr>
  </table>